name: chaleno
description: A package to web scraping data from websites easily and faster using less code lines.
version: 0.0.6
homepage: https://github.com/antonio-nicolau/chaleno

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  http: ">=0.13.0 <1.0.0"
  html: ">=0.15.0 <1.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter